AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  RepositoryName: 
    Type: String
    Description: The name of the CodeCommit repository to create
  CodePipelineS3BucketName:
    Type: String
    Description: The name of the S3 bucket to create that will be used to store artifacts from CodePipeline execution runs.
  CloudFormationDeployActionRoleName:
    Type: String
    Description: The name of the IAM role that will be created to run the CloudFormation deployment action as.
  CodePipelineRoleName:
    Type: String
    Description: The name of the IAM role that will be created for the CodePipeline to use.
  CodePipelineName:
    Type: String
    Description: The name of the CodePipeline to create.
  StageAdministerPipelineStackName:
    Type: String
    Description: The name of this stack that is creating the pipeline. If the names do not match then the pipeline will not be able to update itself.
                                                  
Resources:

  CodeCommitRepository:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: !Join [' ', [!Ref RepositoryName, 'CodeCommit Repository']]

  CodePipelineBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref CodePipelineS3BucketName

  CloudFormationDeployActionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service:
              - cloudformation.amazonaws.com
              - codebuild.amazonaws.com

        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'codebuild:*'
                  - 'codecommit:*'
                  - 'cloudformation:*'
                  - 'codepipeline:*'
                  - 'iam:*'
                  - 's3:*'
                  - 'logs:*'
                Effect: Allow
                Resource: '*'
      RoleName: !Ref CloudFormationDeployActionRoleName 

  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codepipeline-service
          PolicyDocument:
            Statement:
              - Action:
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:CancelUploadArchive

                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild

                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject

                  - cloudformation:GetTemplate
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateStack

                  - 'iam:PassRole'

                Resource: '*'
                Effect: Allow
            Version: 2012-10-17
      RoleName: !Ref CodePipelineRoleName 

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    DependsOn: 
      - CodePipelineRole
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineBucket
      Name: !Ref CodePipelineName
      RestartExecutionOnUpdate: true
      RoleArn: !Join ['', ['arn:aws:iam::',!Ref 'AWS::AccountId',':role/',!Ref CodePipelineRole]]
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeCommit
              OutputArtifacts:
                - Name:  !Join ['', [!Ref RepositoryName, 'Source']]
              Configuration:
                BranchName: 'master'
                RepositoryName: !GetAtt CodeCommitRepository.Name
              RunOrder: 1
        - Name: 'AdministerPipeline'
          Actions:
            - Name: 'AdministerPipeline'
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: REPLACE_ON_FAILURE 
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CloudFormationDeployActionRole, Arn]
                StackName: !Ref StageAdministerPipelineStackName
                TemplateConfiguration: !Join ['', [!Ref RepositoryName, 'Source', '::aws_seed.json']]
                TemplatePath: !Join ['', [!Ref RepositoryName, 'Source', '::aws_seed.yml']]
              InputArtifacts:
                - Name: !Join ['', [!Ref RepositoryName, 'Source']]
              RunOrder: 1
        - Name: 'PackageCfnTemplates'
          Actions:
            - Name: 'DeployPackageCfnCodeBuildProject'
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: REPLACE_ON_FAILURE 
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CloudFormationDeployActionRole, Arn]
                StackName: !Sub "${AWS::StackName}-PackageCfnCodeBuild"
                # TemplateConfiguration: !Join ['', [!Ref RepositoryName, 'Source', '::cfn-templates/packageCfnCodeBuild.json']]
                TemplatePath: !Join ['', [!Ref RepositoryName, 'Source', '::cfn-templates/packageCfnCodeBuild.yml']]
                ParameterOverrides:
                  !Sub
                    - |
                      {"ProjectName": "${AWS::StackName}-PackageCfn",
                       "CodeBuildRoleArn": "${CodeBuildRoleArn}",
                       "S3BucketName": "${CodePipelineS3BucketName}" }
                    - CodeBuildRoleArn: !GetAtt CloudFormationDeployActionRole.Arn
                      S3BucketName: !Ref CodePipelineS3BucketName
              InputArtifacts:
                - Name: !Join ['', [!Ref RepositoryName, 'Source']]
              RunOrder: 1
            - Name: 'PackageCfnTemplates'
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  !Sub "${AWS::StackName}-PackageCfn"
              InputArtifacts:
                - Name: !Join ['', [!Ref RepositoryName, 'Source']]
              OutputArtifacts:
                - Name: CFNTemplateArtifact
              RunOrder: 2
        - Name: 'DeployDev'
          Actions:
            - Name: 'DeployDevInfrastructure'
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: REPLACE_ON_FAILURE 
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CloudFormationDeployActionRole, Arn]
                StackName: !Sub "${AWS::StackName}-master"
                TemplateConfiguration: !Join ['', [!Ref RepositoryName, 'Source', '::dev/master.json']]
                TemplatePath: CFNTemplateArtifact::master.output.yml
              InputArtifacts:
                - Name: CFNTemplateArtifact
                - Name: !Join ['', [!Ref RepositoryName, 'Source']]
              RunOrder: 1

Outputs:
  CodeCommitRepositoryArn:
    Description: CodeCommit Arn
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodeCommitRepositoryArn']]
    Value: !GetAtt CodeCommitRepository.Arn
  CodeCommitRepositoryCloneUrlHttp:
    Description: CodeCommit CloneUrlHttp
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodeCommitRepositoryCloneUrlHttp']]
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp
  CodePipelineBucketArn:
    Description: CodePipeline S3 Bucket Arn
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodePipelineBucketArn']]
    Value: !GetAtt CodePipelineBucket.Arn
  CodePipelineBucketDomainName:
    Description: CodePipeline S3 Bucket DomainName
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodePipelineBucketDomainName']]
    Value: !GetAtt CodePipelineBucket.DomainName
  CodePipelineBucketWebsiteURL:
    Description: CodePipeline S3 Bucket WebsiteURL
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodePipelineBucketWebsiteURL']]
    Value: !GetAtt CodePipelineBucket.WebsiteURL
  CloudFormationDeployActionRoleArn:
    Description: CloudFormationDeployActionRole Arn
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CloudFormationDeployActionRoleArn']]
    Value: !GetAtt CloudFormationDeployActionRole.Arn
  CodePipelineRoleArn:
    Description: CodePipelineRole Arn
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodePipelineRoleArn']]
    Value: !GetAtt CodePipelineRole.Arn
  CodePipelineName:
    Description: CodePipeline Name
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CodePipelineName']]
    Value: !Ref CodePipeline
