AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CloudFormationAssumeRoleName:
    Type: String
    Description: The name of the role that is assumed by the other account to trigger the CloudFormation deployment
  CloudFormationDeployerRoleName:
    Type: String
    Description: The name of the role that performs the CloudFormation deployment
  OtherAwsAccountId:
    Type: String
    Description: The AWS Account ID of the other account that you want to grant cross-account access to.
  OtherAwsAccountKmsKeyArn:
    Type: String
    Description: The arn of the KMS key in the other AWS Account. A shared KMS key is required for access to the S3 bucket containing the build artifacts.
  OtherAwsAccountS3BucketName:
    Type: String
    Description: The name of the S3 bucket in the other account that holds the build artifacts.

Resources:

  CloudFormationAssumeRole:
    Type: AWS::IAM::Role
    DependsOn:
      - CloudFormationDeployerRole
    Properties:
      RoleName: !Ref CloudFormationAssumeRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: [!Ref OtherAwsAccountId]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: cross-account-assume-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'cloudformation:*'
                  - 's3:*'
                  - 'iam:PassRole'
                Resource:
                  - !Join ['', ['arn:aws:s3:::', !Ref OtherAwsAccountS3BucketName]]
                  - !Join ['', ['arn:aws:s3:::', !Ref OtherAwsAccountS3BucketName, '/*']]
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:*'
                  - !GetAtt CloudFormationDeployerRole.Arn
                Effect: Allow
              - Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                Resource:
                   - !Ref OtherAwsAccountKmsKeyArn
                Effect: Allow

  CloudFormationDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CloudFormationDeployerRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - s3.amazonaws.com
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: cross-account-cloudformation-deployment
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: ['s3:*']
                Resource: ['*']
              - Effect: Allow
                Action: ['cloudformation:*']
                Resource: [!Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:*']
              - Effect: Allow
                Action: ['cloudfront:*']
                Resource: ['*']

Outputs:
  CloudFormationAssumeRoleArn:
    Description: CloudFormationAssumeRole Arn
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CloudFormationAssumeRoleArn']]
    Value: !GetAtt CloudFormationAssumeRole.Arn
  CloudFormationDeployerRoleArn:
    Description: CloudFormationDeployerRole Arn
    Export:
      Name: !Join ['', [!Ref 'AWS::StackName', 'CloudFormationDeployerRoleArn']]
    Value: !GetAtt CloudFormationDeployerRole.Arn
