Parameters:
  ProjectName:
    Type: String
    Description: The name of the CodeBuild project to use
  CodeBuildRoleArn:
    Type: String
    Description: Arn of the role to use for the CodeBuild project
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket to deploy packaged CF templates to.
  
Resources:
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Ref "ProjectName"
      Description: Package CloudFormation templates for nested stacks
      ServiceRole: 
        !Ref CodeBuildRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: S3_BUCKET_NAME
            Value: !Ref S3BucketName
            Type: PLAINTEXT
        Image: 'aws/codebuild/ubuntu-base:14.04'
        PrivilegedMode: false
        Type: linuxContainer
      Source:
        BuildSpec: 'buildspec-cfn-package.yml'
        Type: CODEPIPELINE
      TimeoutInMinutes: 10
Outputs:
  ProjectName:
    Description: Codebuild project name
    Value: !Ref CodeBuild
